### ISSUE TITLE
financial_laws.db 如何做出的

### ISSUE THREAD

**Issue by chenboju** [telunyang/python_rag#1]
您好，想請問有關financial_laws.db 的問題
目前在做有關消保法的RAG，法條的部分，要如何用成您這樣呢??

**Comment by telunyang** [comment]
> 您好，想請問有關financial_laws.db 的問題 目前在做有關消保法的RAG，法條的部分，要如何用成您這樣呢??

在範例中，會先蒐集資料，例如在合法的範圍內取得法律與相關條文，再個別儲存至資料庫，可能需要手動或其它機制，將逐個法律內文複製到本機，再用簡單的 SQL 語法逐筆寫入。

`.db` 是用 SQLite 儲存的資料庫檔案，有個簡單的教學在這裡：
[https://github.com/telunyang/python_web_scraping/blob/master/cases/sqlite.ipynb](https://github.com/telunyang/python_web_scraping/blob/master/cases/sqlite.ipynb)

**Comment by chenboju** [comment]
好的了解，謝謝。
